/**
 * AI Citation Tracker — JSON store.
 *
 * Follows the audit-log pattern (load-or-default, validate shape, atomic write,
 * mkdirSync recursive). History is the source of truth; the SOV file is a
 * derived view regenerated by `seoflow sov`.
 *
 * Default paths (from getCitationsPaths()):
 *   .seoflow/data/citations-history.json
 *   .seoflow/data/citations-sov.json
 * Override historyPath in seoflow.config.json → citations.historyPath.
 */
import fs from 'node:fs';
import path from 'node:path';
import { getCitationsPaths } from './config';
import type { CitationHistory, CitationRun, SovSummary } from './types';

function readJson<T>(p: string): T | null {
  if (!fs.existsSync(p)) return null;
  try {
    const raw = JSON.parse(fs.readFileSync(p, 'utf8')) as T;
    if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return null;
    return raw;
  } catch {
    return null;
  }
}

function writeJson(p: string, data: unknown): void {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, JSON.stringify(data, null, 2));
}

function isHistoryShape(v: unknown): v is CitationHistory {
  if (!v || typeof v !== 'object') return false;
  const h = v as Record<string, unknown>;
  return h.version === '1.0' && Array.isArray(h.runs) && typeof h.siteUrl === 'string';
}

function isSovShape(v: unknown): v is SovSummary {
  if (!v || typeof v !== 'object') return false;
  const s = v as Record<string, unknown>;
  return s.version === '1.0' && typeof s.siteUrl === 'string' && typeof s.byTopic === 'object';
}

/** Load citation history (defaults on missing/corrupt file). */
export function loadHistory(historyPath?: string): CitationHistory {
  const p = historyPath ?? getCitationsPaths().historyPath;
  const existing = readJson<unknown>(p);
  if (existing && isHistoryShape(existing)) {
    // Defensive: runs must be an array of run objects.
    existing.runs = existing.runs.filter((r) => r && typeof r === 'object' && Array.isArray(r.probes));
    return existing;
  }
  return { version: '1.0', siteUrl: '', lastRun: null, runs: [] };
}

/** Persist citation history (atomic-ish single write). */
export function saveHistory(history: CitationHistory, historyPath?: string): void {
  const p = historyPath ?? getCitationsPaths().historyPath;
  writeJson(p, history);
}

/** Append a run to history (append-run semantics) and persist. */
export function appendRun(history: CitationHistory, run: CitationRun, historyPath?: string): CitationHistory {
  history.runs.push(run);
  history.lastRun = run.finishedAt;
  saveHistory(history, historyPath);
  return history;
}

/** Load the derived SOV view (defaults on missing/corrupt file). */
export function loadSov(sovPath?: string): SovSummary {
  const p = sovPath ?? getCitationsPaths().sovPath;
  const existing = readJson<unknown>(p);
  if (existing && isSovShape(existing)) return existing;
  return { version: '1.0', siteUrl: '', generatedAt: '', windowRuns: 30, byTopic: {} };
}

/** Persist the SOV view. */
export function saveSov(summary: SovSummary, sovPath?: string): void {
  const p = sovPath ?? getCitationsPaths().sovPath;
  writeJson(p, summary);
}
