/**
 * AI Citation Tracker — shared types.
 *
 * Data shapes follow the research handoff (t_cc28dbec, research-report.md §4):
 * - `.seoflow/data/citations-history.json` is the source of truth (append-run).
 * - `.seoflow/data/citations-sov.json` is a derived view, regenerated by
 *   `seoflow sov` (like structured-output typed sidecars).
 */
import type { CitationBrand } from '../config';

/** Where a probe's answer came from. */
export type ProbeProvider = 'openrouter' | 'gemini-direct' | 'none';

export type ProbeStatus = 'ok' | 'error' | 'skipped-budget' | 'skipped-key';

/** A single detected mention of the site/brand/author inside one answer. */
export interface MentionMatch {
  /** Which rule fired: domain | brand | author */
  matchKind: 'domain' | 'brand' | 'author';
  /** Human-readable pattern source, e.g. "chasingwhereabouts.com" or "Chasing Whereabouts" */
  pattern: string;
  /** Occurrence count at this location (always 1 — deduped distinct matches). */
  count: number;
  /** ±80-char context snippet from the answer (newlines collapsed). */
  context: string;
  /** True when the match sits inside a trailing Sources/References/Links block. */
  inSourcesSection: boolean;
}

/** One brand probe (one topic prompt × one AI brand). */
export interface ProbeResult {
  id: string;
  topic: string;
  prompt: string;
  brand: CitationBrand;
  provider: ProbeProvider;
  modelId: string;
  status: ProbeStatus;
  /** Reason for error/skip. */
  error: string | null;
  startedAt: string;
  latencyMs: number;
  promptTokens: number;
  completionTokens: number;
  /** Estimated USD cost for this probe (from token usage × model pricing). */
  costUsd: number;
  /** First ~400 chars of the model answer (ok probes only). */
  answerSnippet: string;
  /** Count of [N] inline citation markers in the answer text. */
  inlineCitationCount: number;
  /** OpenRouter top-level citations array if ever populated (currently empty — detection scans text). */
  citationsArray: string[];
  mentions: MentionMatch[];
  mentionCount: number;
}

/** One full `seoflow citations` run (a batch of probes). */
export interface CitationRun {
  id: string;
  startedAt: string;
  finishedAt: string;
  /** completed | degraded | failed */
  status: 'completed' | 'degraded' | 'failed';
  config: { freeOnly: boolean; perRunCap: number };
  budget: { callsUsed: number; callsCap: number; costUsd: number };
  probes: ProbeResult[];
}

/** History store — source of truth, append-run semantics. */
export interface CitationHistory {
  version: '1.0';
  siteUrl: string;
  lastRun: string | null;
  runs: CitationRun[];
}

/** Per topic × per AI brand SOV aggregate. */
export interface SovTopicSummary {
  /** Number of probes for this topic+brand in the window (skipped-key included → arrays stay aligned). */
  runs: Record<CitationBrand, number>;
  /** Number of probes where mentionCount >= 1. */
  mentions: Record<CitationBrand, number>;
  /** Share-of-voice metric = mentions / runs. */
  mentionRate: Record<CitationBrand, number>;
  /** ISO timestamp of the newest mentioning run, or null. */
  lastMentioned: Record<CitationBrand, string | null>;
  /** Rolling mention indicator per run (0/1), oldest → newest. */
  trend: Record<CitationBrand, number[]>;
}

/** SOV dashboard — derived view, regenerated from history. */
export interface SovSummary {
  version: '1.0';
  siteUrl: string;
  generatedAt: string;
  windowRuns: number;
  byTopic: Record<string, SovTopicSummary>;
}

/** Brand display labels for console output. */
export const BRAND_LABELS: Record<CitationBrand, string> = {
  chatgpt: 'ChatGPT',
  gemini: 'Gemini',
  perplexity: 'Perplexity',
};

export const BRANDS: CitationBrand[] = ['chatgpt', 'gemini', 'perplexity'];

/** Default new-run status when at least one probe was issued. */
export type RunStatus = CitationRun['status'];
