/**
 * URL Auditor — live SEO audit of a single URL.
 *
 * Uses the existing claude-seo Python scripts (already in scripts/) plus
 * the AI provider to produce a structured SEO audit report.
 *
 * Pipeline:
 *   1. Fetch page signals (fetch_page.py)
 *   2. Run PageSpeed Insights (pagespeed_check.py via psi.ts)
 *   3. Feed signals to AI provider for analysis
 *   4. Return structured audit data
 */
import { execSync } from 'node:child_process';
import path from 'node:path';
import fs from 'node:fs';
import { extractDataBlock, type TechnicalData, isTechnicalData } from './structured-output';
import { appendLog, writeBrain } from './brain';
import { recordAuditRun, recordSignal, initBrain } from './brain/brain-manager';
import { BacklinkAnalyzer } from './backlinks/backlinks';

export interface PageSignals {
  url: string;
  status: number;
  contentLength: number;
  title: string;
  description: string;
  canonical: string;
  h1: string[];
  h2: string[];
  robots: string;
  jsonLd: string[];
  hasSchema: boolean;
  metaRobots: string;
  ogTags: Record<string, string>;
  links: { internal: number; external: number };
  loadTime: number;
  error?: string;
}

export interface GscIndexationStatus {
  indexed: boolean;
  url: string;
  lastCrawled?: string;
}

export interface AutoGeneratedSchema {
  type: string;
  jsonLd: string;
}

export interface PSISummary {
  score: number;
  lcp: number;
  inp: number;
  cls: number;
  fcp: number;
  tbt: number;
}

export interface URLAuditResult {
  url: string;
  signals: PageSignals;
  performance: PSISummary | null;
  report: string;
  data: TechnicalData | null;
  changes: string[];
}

/** Check if a string is a URL */
export function isUrl(s: string): boolean {
  return /^https?:\/\//i.test(s);
}

/** Simple HTML parser for extracting key SEO signals */
function parseHtmlSignals(html: string): {
  title: string; description: string; canonical: string;
  h1: string[]; h2: string[]; jsonLd: string[];
  metaRobots: string; ogTags: Record<string, string>;
  links: { internal: number; external: number };
} {
  const title = (html.match(/<title[^>]*>([^<]+)<\/title>/i)?.[1] || '').trim();
  const descMatch = html.match(/<meta[^>]+name=["']description["'][^>]+content=["']([^"']+)["']/i)
    || html.match(/<meta[^>]+content=["']([^"']+)["'][^>]+name=["']description["']/i);
  const description = descMatch?.[1]?.trim() || '';
  const canonMatch = html.match(/<link[^>]+rel=["']canonical["'][^>]+href=["']([^"']+)["']/i);
  const canonical = canonMatch?.[1]?.trim() || '';
  const robotsMatch = html.match(/<meta[^>]+name=["']robots["'][^>]+content=["']([^"']+)["']/i);
  const metaRobots = robotsMatch?.[1]?.trim() || '';

  const h1: string[] = [];
  const h1Regex = /<h1[^>]*>([\s\S]*?)<\/h1>/gi;
  let m; while ((m = h1Regex.exec(html)) !== null) {
    h1.push(m[1].replace(/<[^>]+>/g, '').trim());
  }

  const h2: string[] = [];
  const h2Regex = /<h2[^>]*>([\s\S]*?)<\/h2>/gi;
  while ((m = h2Regex.exec(html)) !== null) {
    h2.push(m[1].replace(/<[^>]+>/g, '').trim());
  }

  const jsonLD: string[] = [];
  const jsonRegex = /<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;
  while ((m = jsonRegex.exec(html)) !== null) {
    jsonLD.push(m[1].trim());
  }

  const ogTags: Record<string, string> = {};
  const ogRegex = /<meta[^>]+property=["'](og:[^"']+)["'][^>]+content=["']([^"']+)["']/gi;
  while ((m = ogRegex.exec(html)) !== null) {
    ogTags[m[1]] = m[2];
  }

  // Count links
  const allLinks = html.match(/<a[^>]+href=["']([^"']+)["']/gi) || [];
  const baseDomain = canonical ? new URL(canonical).hostname : '';
  let internal = 0, external = 0;
  for (const link of allLinks) {
    const href = link.match(/href=["']([^"']+)["']/)?.[1] || '';
    if (href.startsWith('/') || href.startsWith('.')) internal++;
    else if (href.startsWith('http') && baseDomain && href.includes(baseDomain)) internal++;
    else if (href.startsWith('http')) external++;
    else internal++;
  }

  return { title, description, canonical, h1, h2, jsonLd: jsonLD, metaRobots, ogTags, links: { internal, external } };
}

/** Pure-Node fetch fallback — the npm-installed CLI has no python/ dir, so this is
 *  what makes the zero-setup URL audit actually return signals for strangers. */
async function nodeFetchSignals(url: string): Promise<PageSignals | null> {
  try {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 15000);
    const res = await fetch(url, {
      redirect: 'follow',
      signal: controller.signal,
      headers: { 'user-agent': 'Mozilla/5.0 (SeoFlow URL Auditor)' },
    });
    clearTimeout(timer);
    const raw = await res.text();
    if (!raw) return null;
    const parsed = parseHtmlSignals(raw);
    return {
      url, status: res.status, contentLength: raw.length,
      title: parsed.title, description: parsed.description,
      canonical: parsed.canonical, h1: parsed.h1, h2: parsed.h2,
      robots: '', jsonLd: parsed.jsonLd, hasSchema: parsed.jsonLd.length > 0,
      metaRobots: parsed.metaRobots, ogTags: parsed.ogTags, links: parsed.links, loadTime: 0,
    };
  } catch {
    return null;
  }
}

/** Fetch page signals — uses fetch_page.py (full HTML), render_page.py as fallback for SPA */
async function fetchPageSignals(url: string): Promise<PageSignals> {
  const scriptsDir = path.join(process.cwd(), 'python');

  // Primary: fetch_page.py — returns full HTML, fast, no truncation
  const fetchPath = path.join(scriptsDir, 'fetch_page.py');
  if (fs.existsSync(fetchPath)) {
    try {
      const raw = execSync(`python3 "${fetchPath}" "${url}" 2>/dev/null`, {
        timeout: 20000, encoding: 'utf-8', maxBuffer: 10 * 1024 * 1024,
      });
      const parsed = parseHtmlSignals(raw);
      return {
        url, status: 200, contentLength: raw.length,
        title: parsed.title, description: parsed.description,
        canonical: parsed.canonical, h1: parsed.h1, h2: parsed.h2,
        robots: '', jsonLd: parsed.jsonLd, hasSchema: parsed.jsonLd.length > 0,
        metaRobots: parsed.metaRobots, ogTags: parsed.ogTags, links: parsed.links, loadTime: 0,
      };
    } catch (e) {
      console.log(`     ⚠️  fetch_page.py failed: ${e instanceof Error ? e.message.slice(0, 100) : 'unknown'}`);
    }
  }

  // Fallback: render_page.py for JS-rendered/SPA sites
  const renderPath = path.join(scriptsDir, 'render_page.py');
  if (fs.existsSync(renderPath)) {
    try {
      const raw = execSync(`python3 "${renderPath}" "${url}" --json 2>/dev/null`, {
        timeout: 25000, encoding: 'utf-8', maxBuffer: 10 * 1024 * 1024,
      });
      const data = JSON.parse(raw);
      const html = data.content || '';
      try {
        // Try to get full content from fetch_page.py inside render (without JS deps)
        const fetchRaw = execSync(`python3 "${fetchPath}" "${url}" 2>/dev/null`, {
          timeout: 15000, encoding: 'utf-8', maxBuffer: 10 * 1024 * 1024,
        });
        const parsed = parseHtmlSignals(fetchRaw);
        return {
          url: data.url || url, status: data.status_code || 0,
          contentLength: fetchRaw.length,
          title: parsed.title, description: parsed.description,
          canonical: parsed.canonical, h1: parsed.h1, h2: parsed.h2,
          robots: '', jsonLd: parsed.jsonLd, hasSchema: parsed.jsonLd.length > 0,
          metaRobots: parsed.metaRobots, ogTags: parsed.ogTags, links: parsed.links,
          loadTime: data.render_ms || 0,
        };
      } catch {
        // render-only fallback
        const parsed = parseHtmlSignals(html);
        return {
          url: data.url || url, status: data.status_code || 0,
          contentLength: html.length,
          title: parsed.title, description: parsed.description,
          canonical: parsed.canonical, h1: parsed.h1, h2: parsed.h2,
          robots: '', jsonLd: parsed.jsonLd, hasSchema: parsed.jsonLd.length > 0,
          metaRobots: parsed.metaRobots, ogTags: parsed.ogTags, links: { internal: 0, external: 0 },
          loadTime: data.render_ms || 0,
        };
      }
    } catch (e) {
      console.log(`     ⚠️  render_page.py failed: ${e instanceof Error ? e.message.slice(0, 100) : 'unknown'}`);
    }
  }

  // Pure-Node fallback — no python/ required (npm-installed CLI path)
  const nodeSignals = await nodeFetchSignals(url);
  if (nodeSignals) return nodeSignals;

  return basicFetchSignals(url);
}

/** Basic fallback — fetch URL with raw HTTP */
function basicFetchSignals(url: string): PageSignals {
  try {
    const raw = execSync(`curl -sI -L "${url}" 2>/dev/null | head -20`, { timeout: 10000, encoding: 'utf-8' });
    const statusMatch = raw.match(/HTTP\/[\d.]+ (\d+)/);
    const status = statusMatch ? parseInt(statusMatch[1], 10) : 0;
    return { url, status, contentLength: 0, title: '', description: '', canonical: '', h1: [], h2: [], robots: '', jsonLd: [], hasSchema: false, metaRobots: '', ogTags: {}, links: { internal: 0, external: 0 }, loadTime: 0 };
  } catch {
    return { url: url.replace(/^https?:\/\//, ''), status: 0, contentLength: 0, title: '', description: '', canonical: '', h1: [], h2: [], robots: '', jsonLd: [], hasSchema: false, metaRobots: '', ogTags: {}, links: { internal: 0, external: 0 }, loadTime: 0, error: 'Could not reach URL' };
  }
}

/** Run PageSpeed Insights check */
function runPSI(url: string): PSISummary | null {
  try {
    // Try the Python script first
    const scriptPath = path.join(process.cwd(), 'python', 'pagespeed_check.py');
    if (fs.existsSync(scriptPath)) {
      const raw = execSync(`python3 "${scriptPath}" "${url}" --json 2>/dev/null`, { timeout: 60000, encoding: 'utf-8' });
      const data = JSON.parse(raw);
      return {
        score: data.score ?? 50,
        lcp: data.lcp ?? 0,
        inp: data.inp ?? 0,
        cls: data.cls ?? 0,
        fcp: data.fcp ?? 0,
        tbt: data.tbt ?? 0,
      };
    }
  } catch { /* silent fallback */ }
  return null;
}

/** Check GSC indexation status via gsc_inspect.py */
function checkGscIndexation(url: string): GscIndexationStatus | null {
  try {
    const scriptPath = path.join(process.cwd(), 'python', 'gsc_inspect.py');
    if (!fs.existsSync(scriptPath)) return null;
    const raw = execSync(`python3 "${scriptPath}" "${url}" 2>/dev/null`, { timeout: 30000, encoding: 'utf-8' });
    const lines = raw.split('\n');
    const indexed = lines.some(l => l.toLowerCase().includes('indexed') || l.toLowerCase().includes('submitted'));
    const crawlMatch = raw.match(/last.?crawl.*?(\d{4}-\d{2}-\d{2})/i);
    return { indexed, url, lastCrawled: crawlMatch?.[1] };
  } catch { return null; }
}

/** Auto-generate schema via schema_generate.py */
function autoGenerateSchema(url: string, signals: PageSignals): AutoGeneratedSchema | null {
  try {
    const scriptPath = path.join(process.cwd(), 'python', 'schema_generate.py');
    if (!fs.existsSync(scriptPath)) return null;
    const raw = execSync(`python3 "${scriptPath}" "${url}" 2>/dev/null`, { timeout: 30000, encoding: 'utf-8' });
    const jsonMatch = raw.match(/\{[\s\S]*"@type"[\s\S]*\}/);
    if (!jsonMatch) return null;
    const parsed = JSON.parse(jsonMatch[0]);
    return { type: parsed['@type'] || 'WebPage', jsonLd: JSON.stringify(parsed) };
  } catch { return null; }
}

function buildSignalsOnlyReport(url: string, signals: PageSignals, psi: PSISummary | null): string {
  const titleScore = signals.title && signals.title.length >= 30 && signals.title.length <= 60 ? 90 : signals.title ? 60 : 0;
  const descScore = signals.description && signals.description.length >= 120 && signals.description.length <= 160 ? 90 : signals.description ? 60 : 0;
  const h1Score = signals.h1.length === 1 ? 100 : signals.h1.length === 0 ? 0 : 50;
  const canonicalScore = signals.canonical ? 100 : 0;
  const schemaScore = signals.hasSchema ? 80 : 0;
  const h2Score = signals.h2.length >= 2 ? 90 : signals.h2.length >= 1 ? 60 : 30;
  const psiScore = psi ? psi.score : 0;
  const overallScore = Math.round((titleScore + descScore + h1Score + canonicalScore + schemaScore + h2Score + (psi ? psiScore : 50)) / 7);

  const severitySignals: Array<{ id: string; label: string; severity: 'high' | 'medium' | 'low' | 'info'; detail: string }> = [];
  if (!signals.title) severitySignals.push({ id: 'missing-title', label: 'Missing <title> tag', severity: 'high', detail: 'Every page needs a unique, descriptive title tag' });
  if (!signals.description) severitySignals.push({ id: 'missing-description', label: 'Missing meta description', severity: 'high', detail: 'Meta descriptions drive CTR from search results' });
  if (signals.h1.length === 0) severitySignals.push({ id: 'missing-h1', label: 'Missing H1 heading', severity: 'high', detail: 'Each page needs exactly one H1' });
  if (signals.h1.length > 1) severitySignals.push({ id: 'multiple-h1', label: `${signals.h1.length} H1 tags found`, severity: 'medium', detail: 'Best practice is exactly one H1 per page' });
  if (!signals.canonical) severitySignals.push({ id: 'missing-canonical', label: 'Missing canonical URL', severity: 'medium', detail: 'Canonical prevents duplicate content issues' });
  if (signals.h2.length === 0) severitySignals.push({ id: 'no-h2', label: 'No H2 headings', severity: 'medium', detail: 'H2s provide content structure and keyword signals' });
  if (psi && psi.score < 50) severitySignals.push({ id: 'poor-perf', label: `Low PSI score: ${psi.score}/100`, severity: 'high', detail: `LCP: ${psi.lcp.toFixed(1)}s, CLS: ${psi.cls.toFixed(2)}` });
  if (psi && psi.lcp > 2.5) severitySignals.push({ id: 'lcp-issue', label: `High LCP: ${psi.lcp.toFixed(1)}s`, severity: 'high', detail: 'LCP should be under 2.5 seconds' });
  if (psi && psi.cls > 0.1) severitySignals.push({ id: 'cls-issue', label: `High CLS: ${psi.cls.toFixed(2)}`, severity: 'high', detail: 'CLS should be under 0.1' });
  if (signals.links.internal === 0 && signals.links.external === 0) severitySignals.push({ id: 'no-links', label: 'No links detected', severity: 'low', detail: 'Page may have no outbound links' });

  const high = severitySignals.filter(s => s.severity === 'high').length;
  const medium = severitySignals.filter(s => s.severity === 'medium').length;
  const low = severitySignals.filter(s => s.severity === 'low').length;

  return `## SEO Audit Report — ${url}

**Health Score: ${overallScore}/100** ${overallScore >= 70 ? '✅' : overallScore >= 40 ? '⚠️' : '❌'}

### Score Breakdown
| Category | Score | Status |
|----------|-------|--------|
| Title tag | ${titleScore}/100 | ${titleScore >= 80 ? '✅' : '⚠️'} |
| Meta description | ${descScore}/100 | ${descScore >= 80 ? '✅' : '⚠️'} |
| H1 heading | ${h1Score}/100 | ${h1Score >= 80 ? '✅' : '⚠️'} |
| Canonical URL | ${canonicalScore}/100 | ${canonicalScore >= 80 ? '✅' : '⚠️'} |
| Schema.org | ${schemaScore}/100 | ${schemaScore >= 80 ? '✅' : schemaScore > 0 ? '⚠️' : '❌'} |
| Heading structure | ${h2Score}/100 | ${h2Score >= 80 ? '✅' : '⚠️'} |
| Performance | ${psi ? `${psiScore}/100` : 'N/A'} | ${psi && psiScore >= 70 ? '✅' : psi ? '⚠️' : '—'} |

### Issues Found (${severitySignals.length})
${severitySignals.map(s => `- [${s.severity.toUpperCase()}] ${s.label}: ${s.detail}`).join('\n') || '(none detected)'}

### Raw Signals
| Signal | Value |
|--------|-------|
| HTTP Status | ${signals.status} |
| Title | ${signals.title || '(missing)'} |
| Description | ${(signals.description || '(missing)').slice(0, 160)} |
| Canonical | ${signals.canonical || '(missing)'} |
| Meta Robots | ${signals.metaRobots || '(not set)'} |
| H1 count | ${signals.h1.length} |
| H2 count | ${signals.h2.length} |
| Schema.org | ${signals.hasSchema ? '✅ Present' : '❌ Not found'} |
| Internal links | ${signals.links.internal} |
| External links | ${signals.links.external} |
| Content length | ${(signals.contentLength / 1024).toFixed(1)} KB |
| Load time | ${signals.loadTime}ms |

### H1 Headings
${signals.h1.length ? signals.h1.map(h => `- ${h}`).join('\n') : '(none)'}

### H2 Headings
${signals.h2.length ? signals.h2.slice(0, 20).map(h => `- ${h}`).join('\n') : '(none)'}

### Schema.org Types
${signals.jsonLd.length ? signals.jsonLd.map((j, i) => `- Schema #${i + 1}: \`${j.slice(0, 200)}\``).join('\n') : '(none)'}

### OG Tags
${Object.keys(signals.ogTags).length ? Object.entries(signals.ogTags).map(([k, v]) => `- ${k}: ${v}`).join('\n') : '(none)'}

---
*Set GEMINI_API_KEY, OPENROUTER_API_KEY, or ANTHROPIC_API_KEY for AI-powered analysis with actionable recommendations.*`;
}

const SYSTEM_PROMPT = `You are a Technical SEO Auditor. Given page signals from a URL, produce an SEO audit in Markdown with exactly these sections:

1. Executive summary — 3-5 bullets with [high]/[medium]/[low]/[info] severity tags
2. Indexability — robots meta, canonical, noindex/nofollow, sitemap, hreflang
3. Performance signals — what's visible from HTML (preloads, async/defer, image weight)
4. Security & delivery — HTTPS, HSTS, mixed content
5. Structured data — JSON-LD types, validation issues
6. Crawl & navigation — internal link density, orphan risk
7. Action plan — 5 numbered actions with effort (S/M/L) + impact (S/M/L)

After the action plan, append a fenced code block tagged \`data\` containing JSON:
\`\`\`data
{ "kind": "technical-audit", "v": 1, "url": "<url>", "scores": { "crawl": 0-100, "index": 0-100, "mobile": 0-100, "performance": 0-100, "schema": 0-100 }, "severity_counts": { "high": N, "medium": N, "low": N, "info": N }, "signals": [{ "id": "kebab-case", "label": "Short label", "severity": "high|medium|low|info", "detail": "One sentence" }] }
\`\`\``;

/** Audit a single URL end-to-end */
export async function auditUrl(url: string): Promise<URLAuditResult> {
  const changes: string[] = [];

  console.log(`\n  🌐 Auditing: ${url}`);

  // Step 1: Fetch page signals
  console.log('     📡 Fetching page signals...');
  let signals: PageSignals;
  try {
    signals = await fetchPageSignals(url);
    changes.push(`Fetched ${url} (HTTP ${signals.status})`);
  } catch (e) {
    signals = { url, status: 0, contentLength: 0, title: '', description: '', canonical: '', h1: [], h2: [], robots: '', jsonLd: [], hasSchema: false, metaRobots: '', ogTags: {}, links: { internal: 0, external: 0 }, loadTime: 0, error: e instanceof Error ? e.message : 'Fetch failed' };
    changes.push(`Fetch failed: ${signals.error}`);
  }

  // Step 2: Run PSI
  console.log('     ⚡ Running PageSpeed...');
  const psi = runPSI(url);
  if (psi) {
    changes.push(`PSI score: ${psi.score}/100 (LCP: ${psi.lcp.toFixed(1)}s, CLS: ${psi.cls.toFixed(2)})`);
  } else {
    console.log('     ⚠️  PageSpeed unavailable (no API key?)');
  }

  // Step 2.5: GSC indexation check
  const gscStatus = checkGscIndexation(url);
  if (gscStatus) {
    changes.push(`GSC indexation: ${gscStatus.indexed ? '✅ Indexed' : '❌ Not indexed'}`);
  }

  // Step 2.6: Auto-generate schema if missing
  let autoSchema: AutoGeneratedSchema | null = null;
  if (!signals.hasSchema) {
    autoSchema = autoGenerateSchema(url, signals);
    if (autoSchema) {
      changes.push(`Auto-generated schema: ${autoSchema.type}`);
    }
  }

  // Step 2.7: Backlink analysis (domain-level)
  let backlinksResult: import('./backlinks/backlinks').BacklinkAnalysisResult | null = null;
  try {
    backlinksResult = BacklinkAnalyzer.analyze(url, { includeBing: true, includeMoz: false, includeCommonCrawl: true, limit: 50 });
    if (backlinksResult.totalBacklinks > 0) {
      changes.push(`Backlinks: ${backlinksResult.totalBacklinks} from ${backlinksResult.referringDomains} domains`);
    }
  } catch { /* backlinks optional */ }

  // Step 3: AI analysis (optional — works without it)
  let report = '';
  let data: TechnicalData | null = null;

  try {
    const available = (await import('./providers')).detectAll;
    const all = await available();
    const anyAuthed = all.some(a => a.authed);

    if (!anyAuthed) {
      console.log('     ⚠️  No AI provider available — showing raw signals only');
      report = `## SEO Audit Report — ${url}\n\n` +
        `**HTTP Status:** ${signals.status}\n` +
        `**Title:** ${signals.title || '(missing)'}\n` +
        `**Description:** ${signals.description || '(missing)'}\n` +
        `**Canonical:** ${signals.canonical || '(missing)'}\n` +
        `**H1 count:** ${signals.h1.length}\n` +
        `**H2 count:** ${signals.h2.length}\n` +
        `**Schema.org:** ${signals.hasSchema ? '✅ Found' : '❌ Not found'}\n` +
        `**Meta Robots:** ${signals.metaRobots || '(not set)'}\n` +
        `**Internal links:** ${signals.links.internal}\n` +
        `**External links:** ${signals.links.external}\n` +
        (psi ? `**PSI Score:** ${psi.score}/100 (LCP: ${psi.lcp.toFixed(1)}s, CLS: ${psi.cls.toFixed(2)})\n` : '') +
        `\n---\n*Set GEMINI_API_KEY or ANTHROPIC_API_KEY for AI-powered analysis.*\n`;
    } else {
      console.log('     🤖 AI analysis...');
      try {
        const provider = await (await import('./providers')).selectProvider();
        const result = await provider.chat({
          tier: 'synthesis',
          systemPrompt: SYSTEM_PROMPT,
          messages: [
            { role: 'user', content: `Audit this page. Signals:\n\n\`\`\`json\n${JSON.stringify({
              url: signals.url,
              status: signals.status,
              title: signals.title || '(missing)',
              description: signals.description || '(missing)',
              canonical: signals.canonical || '(missing)',
              h1Count: signals.h1.length,
              h2Count: signals.h2.length,
              hasSchema: signals.hasSchema || !!autoSchema,
              autoSchemaType: autoSchema?.type || null,
              jsonLdTypes: signals.jsonLd.length,
              metaRobots: signals.metaRobots || '(not set)',
              internalLinks: signals.links.internal,
              externalLinks: signals.links.external,
              h1: signals.h1,
              h2: signals.h2,
              gscIndexed: gscStatus?.indexed ?? null,
              gscLastCrawled: gscStatus?.lastCrawled ?? null,
              backlinks: backlinksResult ? {
                total: backlinksResult.totalBacklinks,
                referringDomains: backlinksResult.referringDomains,
                dofollowRatio: backlinksResult.dofollowRatio,
              } : null,
              performance: psi ? { score: psi.score, lcp: psi.lcp, cls: psi.cls } : null,
            }, null, 2)}\n\`\`\`` },
          ],
        });

        if (result?.text) {
          const extracted = extractDataBlock(result.text);
          report = extracted.body;
          if (extracted.data && isTechnicalData(extracted.data)) {
            data = extracted.data;
          }
          changes.push('AI audit analysis complete');
        } else {
          report = buildSignalsOnlyReport(url, signals, psi);
        }
      } catch (e) {
        console.log(`     ⚠️  AI provider failed — showing raw signals`);
        report = buildSignalsOnlyReport(url, signals, psi);
      }
    }
  } catch (e) {
    const msg = e instanceof Error ? e.message : 'Unknown error';
    report = `## Technical SEO Audit — ${url}\n\n**Error:** AI analysis failed — ${msg}\n\n### Raw Signals\n\`\`\`json\n${JSON.stringify(signals, null, 2)}\n\`\`\``;
    changes.push(`AI analysis failed: ${msg}`);
  }

  appendLog({ type: 'run', summary: `URL audit: ${url}`, detail: `${changes.length} data points`, changeCount: changes.length });
  writeBrain({ lastRun: { timestamp: new Date().toISOString(), duration: 0, postsProcessed: 1, errors: report.includes('Error') ? 1 : 0, totalChanges: changes.length } });

  // Record in vault if this isn't just an error stub
  if (signals.url) {
    try {
      const { computeAuditScore, computeSeveritySignals, recordSignal, initBrain, recordAuditRun } = await import('./brain/brain-manager');
      initBrain();
      const computedSignals = computeSeveritySignals(signals, psi);
      const score = computeAuditScore(signals, psi);
      for (const s of computedSignals) {
        recordSignal(url, s.id, s.label, s.severity, s.detail);
      }
      recordAuditRun(url, report, score, computedSignals.length);
    } catch {}
  }

  return { url, signals, performance: psi, report, data, changes };
}